TeangaNLP/teanga

teanga/document.py, tests/test_corpus.py
=> Fix bug with default documents appearing in serialization

teanga/corpus.py, teanga/document.py, teanga/transforms.py, tests/test_corpus.py
=> Implement corpus transformations

teanga/corpus.py, teanga/document.py, teanga/groups.py, tests/test_corpus.py
=> Implement Corpus Grouping

pyproject.toml, teanga/corpus.py, teanga/document.py
=> Implement a query interface

teanga/document.py, tests/test_corpus.py
=> Normalize input layers to list of lists

.github/workflows/python.yml, pyproject.toml, teanga/spacy/__init__.py, teanga/spacy/teanga_spacy.py
=> Add SpaCy service

.github/workflows/static.yml
fixing githubactions dependency installation
=> fixing instead of pip install mkdocs -> poetry with dev req

.github/workflows/static.yml
testing static github actions. fixing indent.
=> fixing indent

teanga/__init__.py, teanga/corpus.py, teanga/transforms.py, tests/test_corpus.py
=> Add `text_corpus` and `parallel_corpus` functions

teanga/corpus.py
Not sure why the previous implementation used a list of pairs. This is more efficient
Fixes #31
=> Change `_docs` to be an dictionary

pyproject.toml, teanga/conllu/__init__.py, teanga/conllu/conllu.py, teanga/corpus.py, teanga/document.py, teanga/utils.py, tests/test_conllu.py, tests/test_corpus.py, tests/test_utils.py
=> Implement CoNLL-U Conversion

teanga/corpus.py
=> Add alignments to `parallel_corpus`

teanga/corpus.py, teanga/rdf.py, teanga/transforms.py, tests/test_corpus.py, tests/test_doc.py
=> Change access to corpus documents

teanga/document.py, tests/test_doc.py
=> Fix setting of metadata layers

teanga/conllu/conllu.py, teanga/utils.py, tests/test_conllu.py, tests/test_utils.py
Better handle issues related to multiple keys and warn on invalid tokenization in UD files
=> Fix CoNLL-U issues

teanga/conllu/conllu.py, tests/test_conllu.py
=> Implement parsing of multi-annotated CoNLLU tokens

teanga/corpus.py, tests/test_corpus.py
Check for all number forms that can occur in YAML
=> Fix integer values

teanga/document.py
=> Better error message for non-string index

teanga/__init__.py, teanga/corpus.py, tests/test_corpus.py
=> Add `download` method

teanga/spacy/teanga_spacy.py, tests/test_spacy.py
=> Apply SpaCY on large paragraphs more effectively

pyproject.toml, teanga/corpus.py, teanga/document.py
=> Add `_repr_html_`

teanga/corpus.py
=> Implement `all` methods

teanga/corpus.py
=> Use CLoader by default

teanga/corpus.py, teanga/document.py
=> Rename Rust integration
